name: WB ETFWorld

on:
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Python 版本的语义版本范围矩阵或准确的版本
        python-version: '3.x' 
        # 可选 - x64 或 x86 架构，默认为 x64
        architecture: 'x64' 
    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip requests
       python -m pip install --upgrade pip pyquery
    # 您可以
    - name: show WBs-ETF
      run: python wbEtf.py
    - name: show WBs-Gsq
      run: python wbGsq.py
